CREATE DATABASE CompanyDb;
GO

USE CompanyDb;

CREATE TABLE Companies (
    ID INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(255) NOT NULL,
    Info NVARCHAR(MAX)
);

CREATE TABLE Departments (
    ID INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(255) NOT NULL
);

CREATE TABLE Positions (
    ID INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(255) NOT NULL,
    DepartmentID INT NOT NULL,
    FOREIGN KEY (DepartmentID) REFERENCES Departments(ID) ON DELETE CASCADE
);

CREATE TABLE Addresses (
    ID INT PRIMARY KEY IDENTITY,
    Address NVARCHAR(255) NOT NULL
);

CREATE TABLE Employees (
    ID INT PRIMARY KEY IDENTITY,
    FullName NVARCHAR(255) NOT NULL,
    Phone NVARCHAR(50),
    BirthDate DATE,
    HireDate DATE NOT NULL,
    Salary DECIMAL(10,2) NOT NULL,
    PositionID INT NOT NULL,
    AddressID INT NOT NULL,
    CompanyID INT NOT NULL,
    FOREIGN KEY (PositionID) REFERENCES Positions(ID) ON DELETE CASCADE,
    FOREIGN KEY (AddressID) REFERENCES Addresses(ID) ON DELETE CASCADE,
    FOREIGN KEY (CompanyID) REFERENCES Companies(ID) ON DELETE CASCADE
);
